        name: DUPLICATE_01

        on:
          workflow_dispatch:


        jobs:
          build:
           name: GITHUB
           runs-on: ubuntu-latest
           steps:
                - name: Check out the repo
                  uses: actions/checkout@v3  
            
#------------------JUNIT
          JUNIT:
           needs: [build]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JUNIT job"
#------------------SELENIUM
          SELENIUM:
           needs: [JUNIT]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an SELENIUM job"
#------------------JMETER
          JMETER:
           needs: [SELENIUM]
           runs-on: ubuntu-latest
           steps:
            - name: Empty Step
              run: echo "This is an JMETER job"
 
    #---------------- APPROVAL_WORKFLOW
          APPROVAL_WORKFLOW:
            needs: [JMETER]
            runs-on: ubuntu-latest
            permissions:
               issues: write
            steps:
               - uses: trstringer/manual-approval@v1
                 with:
                   secret: ${{ secrets.GITHUB_TOKEN }}
                   approvers: DevTester2025
                   issue-title: "Manual Approval"
                   issue-body: "run_id: ${{ github.run_id }}"